# Generated by Django 2.1.dev20180423170307 on 2018-05-01 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=50)),
                ('DescripcionContenido', models.CharField(max_length=100)),
                ('Calidad', models.CharField(max_length=10)),
                ('Puntaje', models.CharField(max_length=2)),
                ('FechaCreacion', models.TimeField()),
                ('FechaObservacion', models.CharField(max_length=10)),
                ('GeneroNoticia', models.CharField(choices=[('P', 'Politica'), ('F', 'Finanzas'), ('C', 'Cultura'), ('L', 'Laboral'), ('D', 'Deportes'), ('E', 'Educacion'), ('O', 'Otro')], default='O', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='PedidoAlta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaPedido', models.DateTimeField(auto_now_add=True)),
                ('NumeroPedido', models.CharField(max_length=5)),
                ('Noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionDeNoticias.Noticia')),
            ],
        ),
        migrations.CreateModel(
            name='Periodista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=20)),
                ('Apellido', models.CharField(max_length=20)),
                ('IdPeriodista', models.CharField(max_length=10)),
                ('CantidadNoticiasEnviadas', models.CharField(max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='pedidoalta',
            name='Periodista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionDeNoticias.Periodista'),
        ),
    ]
