# Generated by Django 2.1.dev20180423170307 on 2018-05-01 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDeNoticias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='Autor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='GestionDeNoticias.Periodista'),
            preserve_default=False,
        ),
    ]
